# **Hold out cv method**

In [1]:
import pandas as pd
import numpy as np

In [2]:
X = [10,20,30,40,50,60,70,80,90,100]

In [3]:
from sklearn.model_selection import train_test_split
train_test_split(X,test_size=0.3,train_size=0.7)

[[100, 40, 90, 70, 30, 10, 50], [80, 60, 20]]

# **LeaveOneOut method**

In [4]:
from sklearn.model_selection import LeaveOneOut

In [5]:
l = LeaveOneOut()

In [6]:
for train, test in l.split(X):
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


# LeavePOut

In [7]:
from sklearn.model_selection import LeavePOut

In [8]:
x=np.array([[1,2],[3,4],[5,6],[7,8]])
y=np.array([1,2,3,4])
l2 = LeavePOut(2)
for train_index, test_index in l2.split(x):
    print("Train : ",train_index, "Test : ",test_index)
    x_train,x_test=x[train_index],x[test_index]
    y_train,y_test=y[train_index],y[test_index]


Train :  [2 3] Test :  [0 1]
Train :  [1 3] Test :  [0 2]
Train :  [1 2] Test :  [0 3]
Train :  [0 3] Test :  [1 2]
Train :  [0 2] Test :  [1 3]
Train :  [0 1] Test :  [2 3]


# Kfold cv method

In [9]:
from sklearn.model_selection import KFold
x=['a','b','c','d','e','f']

kf = KFold(n_splits=3, shuffle=False, random_state=None)

for train, test in kf.split(x):
    
    print("Train data ",train, "Test data ",test)

Train data  [2 3 4 5] Test data  [0 1]
Train data  [0 1 4 5] Test data  [2 3]
Train data  [0 1 2 3] Test data  [4 5]


# StratifiedKFold cv method

In [10]:
from sklearn.model_selection import StratifiedKFold
s = StratifiedKFold(n_splits=3, shuffle=False, random_state=None)
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
y=np.array([1,0,1,0,0,1])

In [11]:
for train_index, test_index in s.split(x,y):
    print("Train : ",train_index, "Test : ",test_index)
    x_train,x_test=x[train_index],x[test_index]
    y_train,y_test=y[train_index],y[test_index]

Train :  [2 3 4 5] Test :  [0 1]
Train :  [0 1 4 5] Test :  [2 3]
Train :  [0 1 2 3] Test :  [4 5]
