# Aim :- Implementation of LASSO Regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Lasso
from sklearn.datasets import make_regression

In [2]:
x,y=make_regression(n_samples=100,n_features=5,n_informative=3,n_targets=1,noise=20,random_state=4)

In [3]:
x

array([[ 2.12370287e-01,  1.14922180e-01,  1.53179086e+00,
        -5.08380228e-01,  1.00598199e+00],
       [ 5.42451308e-01, -6.51225833e-01, -1.10558404e+00,
         4.80062472e-02, -2.35807363e+00],
       [ 3.02902035e-01,  1.80833313e-01, -1.12511459e+00,
         8.50386871e-01, -6.76900945e-01],
       [-9.00395653e-01, -1.68727904e+00, -9.00780945e-01,
         6.13470314e-01,  9.65275392e-04],
       [-4.98720725e-01,  1.19451626e+00,  6.08837219e-01,
        -8.07396136e-02,  1.93787140e+00],
       [ 1.38702576e+00,  5.61836195e-01, -7.66654280e-01,
        -1.08693613e+00, -5.17497227e-02],
       [ 1.88646203e-01,  4.86030067e-02,  9.54698597e-01,
         2.09313488e-01, -3.74444917e-01],
       [-6.80116241e-01,  1.91728485e+00, -1.09591600e+00,
        -1.94573993e-01, -5.80595172e-01],
       [-6.06887283e-01,  3.50997153e-01,  4.61355672e-02,
         1.54697933e+00,  7.23341609e-01],
       [ 5.33652814e-01, -6.51840227e-01, -3.39429436e-01,
         1.00798864e+00

In [4]:
y

array([ 1.78437461e+01, -3.00082902e+01,  3.79738537e+01, -9.10974090e+01,
        9.95367781e+01, -6.15253942e+00,  3.75413906e+01,  1.34990298e+02,
        8.70969658e+01,  5.74060199e+01,  1.48478707e+02,  2.10540823e+01,
        7.09457345e+01, -3.71305572e+00,  4.37209565e+01,  3.21633846e-02,
        8.59605796e+01,  2.33377233e+01, -7.14030750e+01,  4.01716768e+01,
       -1.20739623e+02,  2.40537337e+01, -4.43944432e+01,  6.98723257e+01,
        3.14735050e+00,  1.35001508e+02, -4.54404023e+01, -6.40627501e+01,
        8.90224760e+01, -1.96529900e+01, -1.06668427e+02,  1.15181299e+02,
       -1.38360013e+01, -5.39881124e+01,  1.87816069e+02,  1.06058621e+01,
        1.20654176e+02, -7.80502624e+01,  2.38098269e+02, -7.05544185e+01,
        4.57814519e+01, -6.65031657e+00,  4.92808593e+01, -2.74716257e+01,
        2.28250238e+02,  2.28329390e+01,  6.16109973e+01, -8.14933053e-01,
       -1.32840507e+02,  1.67418674e+02,  3.06611346e+01, -1.43010928e+01,
        8.54364024e+01,  

In [5]:
alphas = [0.001,0.01,0.1,1,2,3,4,5,6,15,20,30,50,80]
for i in alphas:
    l=Lasso(alpha=i)
    l.fit(x,y)
    print(l.coef_) # beta ki values     

[11.63257703 66.91107333 -0.28846809 51.67414714  1.49916141]
[11.620707   66.89846925 -0.2773561  51.66332888  1.48966108]
[11.50188649 66.77270749 -0.16643586 51.55522691  1.39460136]
[10.31701326 65.62422604 -0.         50.63918135  0.2907946 ]
[ 9.15472895 64.34866536  0.         49.59663235  0.        ]
[ 8.03847846 63.06738278  0.         48.53697133  0.        ]
[ 6.92222957 61.78610038  0.         47.4773104   0.        ]
[ 5.80598069 60.50481799  0.         46.41764947  0.        ]
[ 4.6897318  59.22353559  0.         45.35798854  0.        ]
[ 0.         47.38661774  0.         36.04115078  0.        ]
[ 0.         40.66201878  0.         30.97219176  0.        ]
[ 0.         27.21282085  0.         20.83427371  0.        ]
[0.         0.31442499 0.         0.55843761 0.        ]
[0. 0. 0. 0. 0.]


In [6]:
from sklearn.datasets import load_diabetes
cf=load_diabetes(as_frame=True)
p=cf.data
p

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [7]:
q=cf.target
q

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(p,q,test_size=0.25,random_state=2)

In [9]:
alphas = [0.001,0.01,0.1,1,2,3,4,5,6,15,20,30,50]
for i in alphas:
    l=Lasso(alpha=i)
    l.fit(x_train,y_train)
    print(l.coef_) # beta ki values 

[ -35.5620358  -192.89342171  514.70740878  354.34518792 -823.40022324
  540.63269798  122.55704463  132.93153211  822.56229811   53.87372859]
[ -28.52526769 -182.00104562  523.07731571  347.97972944 -436.72192393
  233.05869162  -39.9976906    85.76765881  678.0517396    49.90198068]
[  -0.         -102.73107297  524.8185769   301.45532967  -32.81421264
   -0.         -183.16574065    0.          519.322404      4.86262054]
[  0.           0.         367.89799082  40.10954779   0.
   0.          -0.           0.         346.96960643   0.        ]
[ 0.          0.         63.11085916  0.          0.          0.
 -0.          0.         67.95753777  0.        ]
[ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0. -0.  0.  0. 

**Conclusion** : When we increase the value of alpha the value of coefficient gets penalized ( becomes zero ) hence, it leads to automatic feature selection