In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
data = load_breast_cancer()
df = pd.DataFrame(data.data,columns = data.feature_names)
df['Target'] = data.target

In [3]:
df.head(2)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33            184.6      2019.0   
1                 0.05667  ...          23.41            158.8      1956.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   

   worst symmetry  worst fractal dimension  Target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  

[2 rows x 31 columns]

In [4]:
sample1 = df.sample(200,replace=True)
sample2 = df.sample(200,replace=True)
sample3 = df.sample(200,replace=True) # bootstraping

In [5]:
from sklearn.tree import DecisionTreeClassifier

In [6]:
base_model1 = DecisionTreeClassifier(max_depth=2)
base_model2 = DecisionTreeClassifier(max_depth=2)
base_model3 = DecisionTreeClassifier(max_depth=2) # Agregation

In [7]:
base_model1.fit(sample1.iloc[:,:30],sample1.iloc[:,-1])

DecisionTreeClassifier(max_depth=2)

In [8]:
base_model2.fit(sample2.iloc[:,:30],sample2.iloc[:,-1])

DecisionTreeClassifier(max_depth=2)

In [9]:
base_model3.fit(sample3.iloc[:,:30],sample3.iloc[:,-1])

DecisionTreeClassifier(max_depth=2)

In [10]:
df.sample().values

array([[2.351e+01, 2.427e+01, 1.551e+02, 1.747e+03, 1.069e-01, 1.283e-01,
        2.308e-01, 1.410e-01, 1.797e-01, 5.506e-02, 1.009e+00, 9.245e-01,
        6.462e+00, 1.641e+02, 6.292e-03, 1.971e-02, 3.582e-02, 1.301e-02,
        1.479e-02, 3.118e-03, 3.067e+01, 3.073e+01, 2.024e+02, 2.906e+03,
        1.515e-01, 2.678e-01, 4.819e-01, 2.089e-01, 2.593e-01, 7.738e-02,
        0.000e+00]])

In [11]:
var1 = df.iloc[:,:30].sample(1).values
var1

array([[9.904e+00, 1.806e+01, 6.460e+01, 3.024e+02, 9.699e-02, 1.294e-01,
        1.307e-01, 3.716e-02, 1.669e-01, 8.116e-02, 4.311e-01, 2.261e+00,
        3.132e+00, 2.748e+01, 1.286e-02, 8.808e-02, 1.197e-01, 2.460e-02,
        3.880e-02, 1.792e-02, 1.126e+01, 2.439e+01, 7.307e+01, 3.902e+02,
        1.301e-01, 2.950e-01, 3.486e-01, 9.910e-02, 2.614e-01, 1.162e-01]])

In [12]:
op1 = base_model1.predict(var1)
op1

array([1])

In [13]:
op2 = base_model2.predict(var1)
op2

array([1])

In [14]:
op3 = base_model3.predict(var1)
op3

array([1])

In [15]:
y = np.concatenate((op1,op2,op3))
np.bincount(y).argmax()

1

In [16]:
y = np.concatenate((op1,op2,op3))
y1 = pd.DataFrame(y)
y1

0
0  1
1  1
2  1

In [17]:
y1.mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ()

0
0  1

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn_model1 = KNeighborsClassifier(n_neighbors=5)
knn_model2 = KNeighborsClassifier(n_neighbors=5)
knn_model3 = KNeighborsClassifier(n_neighbors=5)

In [19]:
knn_model1.fit(sample1.iloc[:,:30],sample1.iloc[:,-1])

KNeighborsClassifier()

In [20]:
knn_model2.fit(sample2.iloc[:,:30],sample2.iloc[:,-1])

KNeighborsClassifier()

In [21]:
knn_model3.fit(sample3.iloc[:,:30],sample3.iloc[:,-1])

KNeighborsClassifier()

In [22]:
var1 = df.iloc[:,:30].sample(1).values
var1

array([[1.508e+01, 2.574e+01, 9.800e+01, 7.166e+02, 1.024e-01, 9.769e-02,
        1.235e-01, 6.553e-02, 1.647e-01, 6.464e-02, 6.534e-01, 1.506e+00,
        4.174e+00, 6.337e+01, 1.052e-02, 2.431e-02, 4.912e-02, 1.746e-02,
        2.120e-02, 4.867e-03, 1.851e+01, 3.322e+01, 1.212e+02, 1.050e+03,
        1.660e-01, 2.356e-01, 4.029e-01, 1.526e-01, 2.654e-01, 9.438e-02]])

In [23]:
knn_model1.predict(var1)

array([0])

In [24]:
knn_model2.predict(var1)

array([0])

In [25]:
knn_model3.predict(var1)

array([0])